### ISSUE TITLE
No buffer space available error in `TaskMapper`

### ISSUE THREAD

**Issue by salotz-sitx** [ADicksonLab/wepy#36]
This error was found using the `TaskMapper`:

```
Traceback (most recent call last):
  File "/bgfs01/common/we_envs/envs/wepy_newnodes/lib/python3.7/site-packages/wepy/work_mapper/task_mapper.py", line 490, in run
    self._run_walker()
  File "/bgfs01/common/we_envs/envs/wepy_newnodes/lib/python3.7/site-packages/wepy/work_mapper/task_mapper.py", line 642, in _run_walker
    self._results_list[self.walker_idx] = ('Walker', serial_result)
  File "<string>", line 2, in __setitem__
  File "/bgfs01/common/we_envs/envs/wepy_newnodes/lib/python3.7/multiprocessing/managers.py", line 818, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/bgfs01/common/we_envs/envs/wepy_newnodes/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/bgfs01/common/we_envs/envs/wepy_newnodes/lib/python3.7/multiprocessing/connection.py", line 398, in _send_bytes
    self._send(buf)
  File "/bgfs01/common/we_envs/envs/wepy_newnodes/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 105] No buffer space available
```

Not sure how to approach this or if it is something we can even handle in wepy itself.

**Comment by alexrd** [comment]
Seems like not a wepy issue.  Is this link relevant? https://blog.mphomphego.co.za/blog/2017/06/28/why-am-i-getting-errno105-no-buffer-space-available-when-subscribing-to-multicast-addresses.html

**Comment by salotz-sitx** [comment]
Yep I was too hasty in this issue. Wanted to make sure I didn't forget about it :) I ended up looking at the log and it was just an out of memory error...
